/* Action types */
export const actionTypes = {
  'POSTS_FETCH': 'POSTS/FETCH',
  'POSTS_FETCH_SUCCESS': 'POSTS/FETCH_SUCCESS',
  'POSTS_FETCH_ERROR': 'POSTS/FETCH_ERROR',
  'POSTS_SCROLL': 'POSTS/SCROLL',
  'POSTS_SCROLL_UP': 'POSTS/SCROLL_UP',
  'POSTS_SCROLL_DOWN': 'POSTS/SCROLL_DOWN'
};
