/* Action types */
export const actionTypes = {
  'POSTS_FEATURED_IMAGE_FETCH': 'POSTS/FEATURED_IMAGE/FETCH',
  'POSTS_FEATURED_IMAGE_FETCH_SUCCESS': 'POSTS/FEATURED_IMAGE/FETCH_SUCCESS',
  'POSTS_FEATURED_IMAGE_FETCH_ERROR': 'POSTS/FEATURED_IMAGE/FETCH_ERROR'
};
