/* Action types */
export const actionTypes = {
  'POSTS_FETCH_SINGLE': 'POSTS/FETCH_SINGLE',
  'POSTS_FETCH_SINGLE_SUCCESS': 'POSTS/FETCH_SINGLE_SUCCESS',
  'POSTS_FETCH_SINGLE_ERROR': 'POSTS/FETCH_SINGLE_ERROR'
};
